Filering array

Two ways to filter 
1. masks and fancy indexing 
2. np.where()

boolean masks

In [3]:
import numpy as np
one_to_five = np.arange(1,6)
one_to_five
mask = one_to_five % 2 ==0
mask

array([False,  True, False,  True, False])

filtering with fancy indexing

In [ ]:
import numpy as np
one_to_five = np.arange(1,6)
mask = one_to_five % 2 ==0
one_to_five[mask]


array([2, 4])

2d fancy indexing

In [3]:
import numpy as np
classroom_ids_and_sizes = np.array([[2,22],[2,23],[3,24],[4,26]])
mask=classroom_ids_and_sizes[:,1]%2 ==0
classroom_ids_and_sizes[mask]


array([[ 2, 22],
       [ 3, 24],
       [ 4, 26]])

fancy indexing vs. np.where()
We've seen that fancy indexing returns a filtered array of elements which meet a condition. np-dot-where returns an array of indices of elements which meet the condition. This can be useful when indices are needed later to direct NumPy where to apply code. np-dot-where can also be used for combining data as well as filtering arrays: it can pull different elements into a new array based on whether a condition is met.