In [ ]:
import numpy as np
array = np.array([1, 2, 3])
matrix = np.random.random((2, 3))
print(matrix)
print(array)


[[0.75576327 0.01643301 0.10295379]
 [0.87941508 0.81844054 0.84219882]]
[1 2 3]


In [5]:
import numpy as np
python_list= [2,3,4,5,6,7]
array = np.array(python_list)
print(array)
print(type(array))

[2 3 4 5 6 7]
<class 'numpy.ndarray'>


Creating arrays : np.zeros()

In [6]:
import numpy as np
list = np.zeros((2,3))
print(list)

[[0. 0. 0.]
 [0. 0. 0.]]


Creating arrays : np.random.random()

In [7]:
import numpy as np
list = np.random.random((3,4))
print(list)

[[0.16972037 0.14566988 0.92363508 0.60887716]
 [0.38460735 0.04697466 0.97414713 0.2988133 ]
 [0.52075522 0.74688797 0.40916763 0.52160378]]


Creating arrays with np.arange()

In [9]:
import numpy as np
list = np.arange(-2,3)
print(list)

[-2 -1  0  1  2]
