making 2d array and 3d array

In [2]:
import numpy as np
array_1_2D = np.array([[1,2],[4,6]])
array_2_2D = np.array([[1,2],[4,6]])
array_3_2D = np.array([[1,2],[4,6]])
array_3D = np.array([array_1_2D,array_2_2D,array_3_2D])
print(array_3D)

[[[1 2]
  [4 6]]

 [[1 2]
  [4 6]]

 [[1 2]
  [4 6]]]
