making 2d array and 3d array

In [2]:
import numpy as np
array_1_2D = np.array([[1,2],[4,6]])
array_2_2D = np.array([[1,2],[4,6]])
array_3_2D = np.array([[1,2],[4,6]])
array_3D = np.array([array_1_2D,array_2_2D,array_3_2D])
print(array_3D)

[[[1 2]
  [4 6]]

 [[1 2]
  [4 6]]

 [[1 2]
  [4 6]]]


 4D arrays
Four-dimensional arrays can be harder to visualize since we don't have a fourth dimension. Think of a 4D array as a 2D array filled with 3D arrays.

A vector refers to an array with one dimension

two dimensioal array call matrix

finding the array's shape

In [1]:
import numpy as np
list = np.zeros((3,4))
print(list)
print(list.shape)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)


Flattening an array

In [2]:
import numpy as np
array = np.array([[1,2],[4,6],[6,6]])
print(array)
print(array.flatten())

[[1 2]
 [4 6]
 [6 6]]
[1 2 4 6 6 6]


Reshaping an array
The dot-reshape method allows us to redefine the shape of an array without changing the elements that make up the array. In this example, we take a 2D array with three rows and two columns and change it into a 2D array with two rows and three columns. The shape tuple passed to dot-reshape must be compatible with the number of elements in an array. This array could not be reshaped to a shape of (3, 3), since three times three is nine, and the array has only six elements.

In [4]:
import numpy as np
array = np.array([[1,2],[3,4],[6,7]])
print(array)
print(array.reshape(2,3))

[[1 2]
 [3 4]
 [6 7]]
[[1 2 3]
 [4 6 7]]
