Vectorized operation

In [1]:
import numpy as np
np.arange(100000).sum()

np.int64(4999950000)

Used to add number 3 in 2D array

In [4]:
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
for row in range(array.shape[0]):
    for column in range(array.shape[1]):
        array[row][column] += 3
print(array)

[[4 5 6]
 [7 8 9]]


numpy syntax

In [5]:
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
array + 3

array([[4, 5, 6],
       [7, 8, 9]])