Vectorized operation

In [1]:
import numpy as np
np.arange(100000).sum()

np.int64(4999950000)

Used to add number 3 in 2D array

In [4]:
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
for row in range(array.shape[0]):
    for column in range(array.shape[1]):
        array[row][column] += 3
print(array)

[[4 5 6]
 [7 8 9]]


numpy syntax

In [5]:
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
array + 3

array([[4, 5, 6],
       [7, 8, 9]])

Multiplying two arrays together

In [6]:
import numpy as np
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[0,2,3],[2,4,2]])
array1* array2

array([[ 0,  4,  9],
       [ 8, 20, 12]])

In [7]:
# Not just for math
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
array>2

array([[False, False,  True],
       [ True,  True,  True]])

In [ ]:
import numpy as np
array = np.array(["Numpy","is","AWESOME"])
len(array)>2
# is code is worng in numpy because len is python function not numpy funtion

True

In [9]:
import numpy as np
array = np.array(["Numpy","is","AWESOME"])

vectorized_len = np.vectorize(len)
vectorized_len(array)>2

array([ True, False,  True])